# Generated by Django 5.0.7 on 2024-10-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_vendor_account_number_alter_vendor_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='is_msmse',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
