# Generated by Django 5.1.2 on 2024-10-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_vendor_firm_type_alter_vendor_vendor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='fax',
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_details',
            field=models.FileField(blank=True, null=True, upload_to='bank_details/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='registration_certificates/'),
        ),
    ]
