# Generated by Django 5.1.2 on 2025-04-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_remove_vendor_fax_vendor_bank_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='firm_type',
        ),
        migrations.AddField(
            model_name='vendor',
            name='msme_certificate',
            field=models.FileField(blank=True, null=True, upload_to='msme_certificates/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pan_document',
            field=models.FileField(blank=True, null=True, upload_to='pan_documents/'),
        ),
    ]
