# Generated by Django 5.1.7 on 2025-04-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_remove_vendor_firm_type_vendor_msme_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='requesting_lakshya_department',
            field=models.CharField(blank=True, choices=[('Admin Department', 'Admin Department'), ('IT Department', 'IT Department'), ('Marketing Department', 'Marketing Department'), ('Academic Department', 'Academic Department'), ('Finance/Legal Department', 'Finance/Legal Department'), ('HR Department', 'HR Department')], max_length=50, null=True, verbose_name='Requesting Lakshya Department'),
        ),
    ]
